#!/usr/bin/env bash
#Participant to enter their details here:

name="name"
Roll_no="*************"
branch="*****"
mail="*********"
phone="*********"
remarks="********"
#enter anything you want to add

echo $name " | " $Roll_no " | " $branch " | " $remarks
echo $mail - $phone
