#!/usr/bin/env bash
#Participant to enter their details here:

name=" Siri Kondapi"
Roll_no="16010125112"
branch="COMPS"
mail="siri.kondapi@somaiya.edu"
phone="8104140658"
remarks="Since only 3 tries a day is allowed for VM in labex it's been done using multiple accounts."
#enter anything you want to add


echo $name " | " $Roll_no " | " $branch " | " $remarks
echo $mail - $phone
